name: Build and deploy Python app to Azure Web App - discountcard-python

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Create venv and upgrade pip
        shell: bash
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip

      # Build LightFM & deps locally and vendor into .python_packages
      - name: Vendor site-packages to .python_packages
        shell: bash
        env:
          LIGHTFM_NO_OPENMP: "1"
        run: |
          . venv/bin/activate
          pip install "Cython<3" "setuptools<75" wheel
          pip install "numpy==1.26.4" "scipy==1.11.4"
          mkdir -p .python_packages/lib/site-packages
          pip install --no-build-isolation --no-deps --target .python_packages/lib/site-packages "lightfm==1.17"
          pip install --no-deps --target .python_packages/lib/site-packages -r requirements.txt
          pip install --target .python_packages/lib/site-packages "numpy==1.26.4" "scipy==1.11.4"
          python -c "import sys,os; p=os.path.abspath('.python_packages/lib/site-packages'); sys.path.insert(0,p); import lightfm,numpy,scipy; print('Vendored OK', numpy.__version__, scipy.__version__, lightfm.__version__)"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_953B5F4DDC3B40929CC29CB1320B46B6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A27DC4B3F014B07BF539AEB7BEF1082 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_31D9862E0333485683F6E01E6070820D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "discountcard-python"
          slot-name: "Production"
          package: .
